name: condaenv
channels:
  - conda-forge
  - defaults
dependencies:
  - av=9.2.0
  - cudnn=8.2.1.32
  - cython=0.29.32
  - faiss-gpu=1.7.2
  - fastai::fastai=2.7.10
  - ffmpeg-python=0.2.0
  - h5py=3.7.0
  - loguru=0.6.0
  - libtiff=4.4.0
  - matplotlib=3.6.2
  - networkx=2.8.8
  - numba=0.56.3
  - numpy=1.23.4
  - nvidia::cudatoolkit=11.3.1
  - opencv=4.6.0
  - oss2=2.16.0
  - pandas=1.5.1
  - pillow=8.4.0
  - pip=22.3.1
  - pytest=7.2.0
  - python-magic=0.4.27
  - python=3.9.13
  - pytorch::pytorch=1.12.1=py3.9_cuda11.3_cudnn8.3.2_0
  - pytorch::torchaudio=0.12.1=py39_cu113
  - pytorch::torchvision=0.13.1=py39_cu113
  - scikit-image=0.19.3
  - scikit-learn=1.1.3
  - scipy=1.9.3
  - setuptools=59.5.0
  - tqdm=4.64.1
  - tslearn=0.5.2
  - pip: 
    - augly[image,video]==1.0.0
    - lightning-flash[video,image]==0.8.1
    - pytorch-lightning==1.8.6
    - pytorchvideo==0.1.2
    - segmentation-models-pytorch==0.3.2
    - tensorflow-gpu==2.9.1
    - timm==0.6.12
    - transformers==4.25.1